# organization name, it's used to get github repo url, also in page title
name: expressjs

# badge style, can be "flat" or ""
# see https://badgen.net/ for details
badge_style: flat

# meta headers in html
title:       ExpressJS
description: Node/Express utilities and middleware
keywords:    express

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - cors
 - body-parser
 - session
 - generator:
     npm: express-generator
 - cookie-parser
 - errorhandler
 - timeout
 - cookie-session
 - compression
 - serve-index
 - errorhandler
 - body-parser
 - serve-favicon
 - csurf
 - morgan
 - serve-static
 - method-override
 - multer
 - response-time
 - flash
 - session:
     npm: express-session
 - vhost

# list of maintainers, this won't be sorted
maintainers:
 - name:    Doug Wilson
   github:  dougwilson   # github account, required: we link to it
   npm:     dougwilson   # npm account, required to determine lead maintainer
   twitter: blipsofadoug # twitter account, optional
   email:   doug@somethingdoug.com

 - name:    Jonathan Ong
   github:  jonathanong
   npm:     jongleberry
   twitter: jongleberry
   email:   me@jongleberry.com

   # if gravatar is attached to an email different from specified above,
   # add md5 of it here:
   avatar:  6e33cc0412b61cc01daac23c8989003c

 - name:    Jeremiah Senkpiel
   github:  fishrock123
   npm:     fishrock123
   twitter: fishrock123
   email:   fishrock123@rocketmail.com

 - name:    Alex Kocharin
   github:  rlidwka
   npm:     rlidwka
   twitter: rlidwka
   email:   alex@kocharin.ru

 - name:    Linus Unnebäck
   github:  LinusU
   npm:     linusu
   twitter: LinusU
   email:   linus@folkdatorn.se

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
